version: '3.5'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - hackernews_ops
    volumes:
      - type: bind
        source: .
        target: /app

networks:
  hackernews_ops:
    external: true

